[package]
name = "forest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.18"
cpal = "0.13.5"
anyhow = "1.0.57"
rand = "0.8.5"
ctrlc = "3.2.2"
